title: "Lincoln Mullen"
description: "Lincoln Mullen is a historian of American religion and the nineteenth-century United States."

mediaTypes:
  application/feed+json:
    suffixes: ["json"]

outputFormats:
  JSONFeed:
    mediaType: "application/feed+json"
    baseName: "index"
    isPlainText: false
    rel: "alternate"

permalinks:
  blog: "/:section/:slug/"
  archive: "/:slug/"
  page: "/:section/:slug/"
  links: "/:section/:year-:01-:02-:03-:04-:05/"
  newsletter: "/:section/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
    lineNos: true
    tabWidth: 2

imaging:
  quality: 85

params:
  blogFeedTitle: "Lincoln Mullen's blog"
  subtitle: "Historian of American religion"
  newsletterTitle: "Working on It"
  siteFeedUrl: "/blog/index.xml"
  author:
    name: "Lincoln Mullen"
    email: "lincoln@lincolnmullen.com"

taxonomies: false

enableGitInfo: true

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^BLOG_
